-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 23:19:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema controledejogos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema controledejogos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controledejogos` DEFAULT CHARACTER SET utf8 ;
USE `controledejogos` ;

-- -----------------------------------------------------
-- Table `controledejogos`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controledejogos`.`Usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `foto` VARCHAR(90) NULL,
  `email` VARCHAR(90) NOT NULL,
  `senha` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controledejogos`.`Administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controledejogos`.`Administradores` (
  `id` INT NOT NULL,
  `nome` VARCHAR(90) NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controledejogos`.`Jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controledejogos`.`Jogos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NULL,
  `descricao` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controledejogos`.`JogosDosUsuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controledejogos`.`JogosDosUsuarios` (
  `Usuarios_id` INT NOT NULL,
  `Jogos_id` INT NOT NULL,
  `highscore` DOUBLE NULL,
  `tempodejogo` DOUBLE NULL,
  PRIMARY KEY (`Usuarios_id`, `Jogos_id`),
  INDEX `fk_Usuarios_has_Jogos_Jogos1_idx` (`Jogos_id` ASC)  ,
  INDEX `fk_Usuarios_has_Jogos_Usuarios_idx` (`Usuarios_id` ASC)  ,
  CONSTRAINT `fk_Usuarios_has_Jogos_Usuarios`
    FOREIGN KEY (`Usuarios_id`)
    REFERENCES `controledejogos`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Jogos_Jogos1`
    FOREIGN KEY (`Jogos_id`)
    REFERENCES `controledejogos`.`Jogos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controledejogos`.`fases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controledejogos`.`fases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Jogos_id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `fasescol` VARCHAR(45) NULL,
  `secfase` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fase_Jogos1_idx` (`Jogos_id` ASC)  ,
  CONSTRAINT `fk_fase_Jogos1`
    FOREIGN KEY (`Jogos_id`)
    REFERENCES `controledejogos`.`Jogos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controledejogos`.`itensjogo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controledejogos`.`itensjogo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fase_id` INT NOT NULL,
  `nome` VARCHAR(90) NULL,
  `foto` VARCHAR(90) NULL,
  `forca` DECIMAL NULL,
  `valor` DECIMAL NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_itensjogo_fase1_idx` (`fase_id` ASC)  ,
  CONSTRAINT `fk_itensjogo_fase1`
    FOREIGN KEY (`fase_id`)
    REFERENCES `controledejogos`.`fases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controledejogos`.`itensjogosdousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controledejogos`.`itensjogosdousuario` (
  `Usuarios_id` INT NOT NULL,
  `Jogos_id` INT NOT NULL,
  `itensjogo_id` INT NOT NULL,
  `quantidade` DECIMAL NULL,
  PRIMARY KEY (`Usuarios_id`, `Jogos_id`, `itensjogo_id`),
  INDEX `fk_JogosDosUsuarios_has_itensjogo_itensjogo1_idx` (`itensjogo_id` ASC)  ,
  INDEX `fk_JogosDosUsuarios_has_itensjogo_JogosDosUsuarios1_idx` (`Usuarios_id` ASC, `Jogos_id` ASC)  ,
  CONSTRAINT `fk_JogosDosUsuarios_has_itensjogo_JogosDosUsuarios1`
    FOREIGN KEY (`Usuarios_id` , `Jogos_id`)
    REFERENCES `controledejogos`.`JogosDosUsuarios` (`Usuarios_id` , `Jogos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JogosDosUsuarios_has_itensjogo_itensjogo1`
    FOREIGN KEY (`itensjogo_id`)
    REFERENCES `controledejogos`.`itensjogo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controledejogos`.`fasesJogosDosUsuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `controledejogos`.`fasesJogosDosUsuarios` (
  `JogosDosUsuarios_Usuarios_id` INT NOT NULL,
  `JogosDosUsuarios_Jogos_id` INT ZEROFILL NOT NULL,
  `fases_id` INT NOT NULL,
  `finalizada` TINYINT NULL,
  `highscore` DOUBLE NULL,
  `didponivel` TINYINT NULL,
  PRIMARY KEY (`JogosDosUsuarios_Usuarios_id`, `JogosDosUsuarios_Jogos_id`, `fases_id`),
  INDEX `fk_JogosDosUsuarios_has_fases_fases1_idx` (`fases_id` ASC)  ,
  INDEX `fk_JogosDosUsuarios_has_fases_JogosDosUsuarios1_idx` (`JogosDosUsuarios_Usuarios_id` ASC, `JogosDosUsuarios_Jogos_id` ASC)  ,
  CONSTRAINT `fk_JogosDosUsuarios_has_fases_JogosDosUsuarios1`
    FOREIGN KEY (`JogosDosUsuarios_Usuarios_id` , `JogosDosUsuarios_Jogos_id`)
    REFERENCES `controledejogos`.`JogosDosUsuarios` (`Usuarios_id` , `Jogos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_JogosDosUsuarios_has_fases_fases1`
    FOREIGN KEY (`fases_id`)
    REFERENCES `controledejogos`.`fases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
